print('Escreva dois números para realizar a soma')
numero1 = input('digite o primeiro número:')
numero2 = input('digite o segundo número:')
print('o resultado de', numero1, 'somado com', numero2, 'é:')
print(numero1 + numero2)
